[build-system]
requires = ["uv_build>=0.12.1,<0.13"]
build-backend = "uv_build"

[project]
name = "easysaxo"
version = "1.0.53.2"
description = "EasySaxo Alpha Edition, mini-shell CLI that works with your system commands as well!"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "SXF", email = "saxalinka2@gmail.com" }
]
keywords = ["ezsx", "EaSa", "SXF"]
dependencies = [
    "colorama>=0.4.6",
    "rich>=13.0.0",
    "psutil>=5.9.0",
    "pygame-ce>=2.4.0",
    "uv>=0.1.0",
    "prompt-toolkit>=3.0.0",
    "py-cpuinfo>=9.0.0",
    "speedtest-cli>=2.1.3",
    "cputil>=1.0.0",
    "gputil>=1.4.0",
    "ascii-magic>=2.3.0",
    "bcrypt>=5.0.0",
    "scikit-learn>=1.9.0",
    "art>=6.5",
    "numpy>=2.5.1",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Other Audience",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Programming Language :: Python :: 3.13",
    "Topic :: Desktop Environment :: File Managers"
]

[project.optional-dependencies]
ml = [
    "scikit-learn>=1.9.0",
]

[project.scripts]
easysaxo = "easysaxo.main:run"
